# Site
repository: kaito1410/kaito1410.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Steven Zhu
title: Software Developer
email: kaito1410@gmail.com
website: www.github.com/kaito1410/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  kaito1410
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: steven-zhu-waterloo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube channel link doesn't work until you have a custom channel link
# youtube_username: channel/UCd7f4bFuV6iXzJtyiAp3Kzw
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: youtube
  icon: fab fa-youtube
  url: https://www.youtube.com/channel/UCd7f4bFuV6iXzJtyiAp3Kzw
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Steven and I'm a backend software developer. My favorite language is <mark>C++</mark> due to it's scalability and efficiency. <mark>Python</mark> is a close second due to its flexibilty and ease of use. I have worked at multiple companies gaining valuable experience and teamwork skills. I'm proficient with working in large code bases and integrating 3rd party solutions via API. I'm also familiar with Git, as I use it both for work and personal projects.  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: AutoDD-Rev2
        link: github.com/kaito1410/AutoDD_Rev2
        # link_text: Project Website
        additional_links:
          - title:  A website that uses my AutoDD-Rev2 python script
            icon: fab fa-github
            url: http://unbiastock.com/reddit.php
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A little side project of mine.
        description: | # this will include new lines to allow paragraphs
          I started investing and building an investment portfolio a year ago. For a period of time, I was deeply interested in penny stocks but had no idea where to find new tickers. After discovering a subreddit called [r/pennystocks](https://www.reddit.com/r/pennystocks/), I would end up reading the subreddit for hours everyday. One day, a reddit user created a python script which counts the number of mentions of a stock ticker on r/pennystocks. Since then, I have taken over the project and added many features and functionalities over the original script, hence <mark>r/AutoDD-Rev2</mark> was born. Some notable features include adding yahoo finance integration, implementing a scoring system based on upvotes and reddit flair, supporting multiple subreddits, an option to sort results, and an option to output as CSV. The source code is [here](https://github.com/kaito1410/AutoDD_Rev2) and a webapp of the script in action, created by another reddit user can be found [here](https://www.reddit.com/r/CanadianInvestor/comments/l24d34/most_trending_stocks_in_reddit_by_sub_thread/).

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Safe Software
        link: https://www.safe.com/
        # link_text: boringcompany.com
        sub_title: Software Developer
        caption: November 2017 - Present
       # quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            My role at Safe Software is to develop <mark>data integration</mark> and <mark>data conversion tools</mark> for FME Desktop. I worked in a large codebase that mainly uses <mark>C++</mark>, and my expertise is parsing and processing XML and JSON data types. The projects that I was in charge of are [12d Model](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_ReadersWriters/12dxml/12dxml.htm), [TopoJSON](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_ReadersWriters/topojson/topojson.htm), [QVX Writer](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_ReadersWriters/qvx/qvx.htm), [Qlik Connector](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_ReadersWriters/qlikjson/qlikjson.htm), [OGC WCS](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_ReadersWriters/wcs/wcs.htm), and [OGC WMTS](http://docs.safe.com/fme/2021.0/html/FME_Desktop_Documentation/FME_ReadersWriters/wmts/wmts.htm)

      - layout: left
        title: Milliman Inc.
        link: https://us.milliman.com/en/
        # link_text: boringcompany.com
        sub_title: Software Developer Intern
        caption: August 2016 - December 2016
       # quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            My role at Milliman was to develop <mark>automation solutions</mark> for their business processes. The underlying library used was an open source scheduler called [Quartz.NET](https://www.quartz-scheduler.net/) and the solution was mainly developed using <mark>C#</mark>. The scheduler was to be controled via command line which would be executed from one of their internal webapp. 

      - layout: left
        title: D+H Limited Partnership
        link: https://en.wikipedia.org/wiki/D%2BH
        # link_text: boringcompany.com
        sub_title: Software Developer Intern
        caption: January 2016 - April 2016
       # quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            My role at D+H was to improve and add features to their internal webapp. On the backend, I used a combination of <mark>C#</mark> and <mark>SQL stored procedures</mark> to add, query, modify, or delete information from their database. On the frontend, I developed new pages using <mark>ASP.NET</mark> to interact with the backend. In addition, I created a new table which keeps a history of operations made by users that uses the webapp, so operations could be reverted if needed. 

      - layout: left
        title: TD Securities
        link: https://www.tdsecurities.com/ca/en/home-page
        # link_text: boringcompany.com
        sub_title: Software Developer Intern
        caption: January 2015 - April 2015
       # quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            My role at TD Securities was mainly fixing bugs in their large codebase. Most of the codebase was written with C# and some C++. At the end of my internship, I created an <mark>automation script</mark> that installs of a list of financial software. Once the userid was passed into the script, the script would pull the user's role information from the employees database and decide which software(s) to install.  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Waterloo
        caption: September 2012 - August 2017
        sub_title: Bachelor of Computer Science And Bachelor of Business Administration Double Degree
        #quote: >
         # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
    #    description: | # this will include new lines to allow paragraphs
     #     During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
    #
      #    I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software development, some of my other hobbies are:
      - Badminton
      - Gaming
      - Cars
      - Videography/Photography
      - [Youtuber](https://www.youtube.com/channel/UCd7f4bFuV6iXzJtyiAp3Kzw)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
